Repository The-Mycelium-Network/webworkbook, pull requests merged in 2022-12, with the labels that each got.

#75 Webworkbook coyag branch 3
  content/topics/what-is-the-internet/who-controls-the-internet/index.md
Labels: technical-writing

#83 chore: netlify config
  .gitignore
  netlify.toml
Labels: chore

#59 Added content about web browsers
  content/topics/what-is-a-web-browser/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#85 feat: main content template implementation
  assets/css/organisms/content-page-header.css
  assets/css/site.css
  assets/css/views/content.css
  content/topics/_index.md
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/partials/content-page-header.html
  layouts/partials/sidebar-navigation.html
  layouts/partials/sidebar.html
Labels: enhancement

#56 Different types of internet connections
  content/topics/types-of-connections/index.md
  content/topics/types-of-connections/speed-chart.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#88 schalk/mec 265 integrate tina
  .gitignore
  .tina/config.js
  content/posts/hello-world.md
  package-lock.json
  package.json
Labels: chore

#96 chore(actions): add pr lint action
  .github/workflows/pr-title-linter.yml
  CONTRIBUTING.md
  README.md
Labels: chore

#98 chore: add release please
  .github/workflows/changelog-ci-config.json
  .github/workflows/pr-title-linter.yml
  .github/workflows/release-please.yml
Labels: chore

#99 chore(main): release 1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
