Repository The-Mycelium-Network/webworkbook, pull requests merged in 2022-10, with the labels that each got.

#27 Added what-is-git file with index.md
  content/topics/what-is-git/index.md
Labels: chore, hacktoberfest, hacktoberfest-accepted

#33 Add TCP and IP protocols
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted

#31 UDP
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted

#32 chore: add contribution guidelines document
  CONTRIBUTING.md
  README.md
Labels: chore

#35 chore: fix site title
  config.toml
Labels: chore

#36 Edited titles of topic pages
  content/topics/_index.md
  content/topics/protocols/index.md
  content/topics/what-is-open-source/index.md
  content/topics/what-is-the-internet/index.md
Labels: bug, hacktoberfest, hacktoberfest-accepted

#45 chore: add changelog generator action
  .github/dependabot.yml
  .github/workflows/changelog-ci-config.json
  .github/workflows/changelog-ci.yml
Labels: chore

#34 design: add brand assets
  brand-assets/logo.ai
  brand-assets/logo.png
  brand-assets/logo.svg
  brand-assets/logo@2x.png
Labels: design

#47 bug: fix version number
  .github/workflows/changelog-ci.yml
Labels: bug

#41 Content: Rephrase SMTP protocol
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#40 24 adding pop3
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#54 24 - Adding SFTP to the protocols
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#57 Create hugo.yml
  .github/workflows/hugo.yml
Labels: chore

#55 24 - adding - SSH
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#43 docs: what is GitHub introduction
  content/topics/what-is-github/index.md
Labels: hacktoberfest, hacktoberfest-accepted

#46 chore: what is GitHub - GitHub alternatives
  content/topics/what-is-github/index.md
Labels: technical-writing

#61 bug: fix youtube embed
  content/topics/what-is-github/index.md
Labels: bug

#48 37 - Create SVG topic
  content/topics/web-development/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#42 Adding updated What is Git? index.md file
  content/topics/what-is-git/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#69 chore: add project charter to readme
  README.md
Labels: chore, documentation

#67 24 adding SSL with updated info
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing

#58 24 adding DNS to the protocols
  content/topics/protocols/index.md
Labels: hacktoberfest, hacktoberfest-accepted, technical-writing
